name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        run: echo "3932Nisha4413@" | docker login -u "rathorenisha499@gmail.com" --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t nishi31/petclinic00:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push nishi31/petclinic00:latest
